//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group17_iCAREAPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TreatmentRecord
    {
        public string treatmentID { get; set; }
        public string description { get; set; }
        public System.DateTime treatmentDate { get; set; }
        public string patientID { get; set; }
        public string workerID { get; set; }
    
        public virtual iCAREWorker iCAREWorker { get; set; }
        public virtual PatientRecord PatientRecord { get; set; }

        public static List<string> getPatientIDs(Group17_iCAREDBEntities db, string workerId)
        {
            return db.TreatmentRecord
                .Where(p => p.workerID == workerId)
                .Select(p => p.patientID)
                .ToList();
        }
    }
}
